= Gas vs sFUEL

== What is gas? 


Gas is a tokenized asset that enables a blockchain network to function, similarly to how fuel enables a car to function. It is the mechanism that moves the network forward. 

In more technical terms from link:https://ethereum.org/en/developers/docs/gas/#what-is-gas[https://ethereum.org] --

"Gas refers to the unit that measures the amount of computational effort required to execute specific operations on the Ethereum network."

== It's different on SKALE

***Ether*** is the gas token for the Ethereum Network. ***sFUEL*** is the gas token for the SKALE Network. While these are both gas tokens, there are some important, key differences that enable SKALE to operate with zero-cost transactions. 

There is no cost for sFUEL, it has **absolutely no economic value**. It is free metered resources for transactions on the network. link:https://skale.space/blog/validator-economics[To undestand why SKALE doesn't need users to pay gas fees]



== Gas vs sFUEL

<add table>

=== Easy Access

Easy access to sFUEL is one of the key reasons why SKALE can enable projects to build invisible blockchain experiences. Accessibility at scale is available with sFUEL since it is not minable, it is not purchasable, and it can be distributed for free resulting in easy access for all.

=== No Economic Value

Gas is a common topic of discussion within the blockchain space due to variable fees that can make using networks unsustainable for many. The lack of economic value enables SKALE Chains and the dApps built on them to have stable or even free costs [if the dApp does not charge for usage]. This makes accessing blockchain technology and related applications a realistic option for more people than ever before.


Additionally, valued assets can often be a large blocker for applications looking to leverage blockchain technologies. While subsidizing fees can be used by projects to hide costs from end users, spikes in blockchain usage can cause high fees resulting in applications being unable to function. 

=== Not Purchasable

Purchasable tokens represent one of the largest barriers to entry into the blockchain space. Most users expect services to "just work" and onboarding experiences to let them login with an existing service and start using or playing in seconds. For many networks, the login portion can be hidden away with third party services, however, the gas fees cannot. Users are required to go to other applications or services to purchase assets to transact in. Additionally, users often have to spend money just to transfer tokens to a new network. 

Non-purchasable tokens remove that friction entirely. If they cannot be purcahsed, then they must be given. Learn more about how xref:./sfuel-distribution.adoc[works].
